---
version: 2.0

jobs:
  readme:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./tests
      - run:
          command: npm test
          working_directory: ./tests

  ts:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./ts/example
      - run:
          command: npm test
          working_directory: ./ts/example

  swift:
    docker:
      - image: swift:5.1.5
    steps:
      - checkout
      - run:
          command: swift test --enable-test-discovery
          working_directory: ./swift/example

  d:
    build:
      working_directory: ~/vanilla-mock-manifesto/d/example
      docker:
        - image: dlang2:dmd-circleci
    steps:
      - checkout
      - run: dub test

workflows:
  version: 2
  test_all:
    jobs:
      - readme
      - ts
      - swift
      - d
